# Generated by Django 5.0.7 on 2024-07-13 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.IntegerField(unique=True)),
                ('fecha_emision', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre_mecanico', models.CharField(max_length=255)),
                ('resultado', models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('condicional', 'Condicional')], default='rechazado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=7, unique=True)),
                ('categoria', models.CharField(choices=[('l', 'menos de 4 ruedas'), ('m', '4 ruedas o mas, menos de 1 tonelada, pasajeros'), ('n', '4 ruedas o mas, menos de 1 tonelada, carga'), ('o', 'acoplados')], default='m', max_length=2)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('primera_rto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('rel_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='realizar_pago.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='rel_rto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='realizar_pago.rto'),
        ),
        migrations.AddField(
            model_name='rto',
            name='rel_vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realizar_pago.vehiculo'),
        ),
    ]
