# Generated by Django 5.0.7 on 2024-08-27 17:39

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_mecanico', models.CharField(max_length=255)),
                ('resultado', models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('condicional', 'Condicional')], default='rechazado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nro', models.IntegerField()),
                ('cod_seguridad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=10, populate_from='id', unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('rel_rto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto', to='realizar_pago.rto')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('primera_rto', models.BooleanField(default=True)),
                ('rel_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='realizar_pago.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='rto',
            name='rel_vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realizar_pago.vehiculo'),
        ),
    ]
