# Generated by Django 5.0.7 on 2024-07-14 22:41

import cu.realizar_pago.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizar_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nro', models.BigIntegerField(validators=[cu.realizar_pago.models.validar_rango])),
                ('cod_seguridad', models.IntegerField(max_length=3)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
