# Generated by Django 5.0.7 on 2024-07-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizar_pago', '0002_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='cod_seguridad',
            field=models.IntegerField(),
        ),
    ]
